coverage:
  precision: 2
  round: down
  range: 0...100
  status:
    changes: false
    patch: true
    project: true
  ignore:
    - "Tests/.*"

comment:
  behavior: default
  layout: header, diff
  require_changes: false