os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode9
script:
  - eval "$(curl -sL https://raw.githubusercontent.com/swixbase/ciscript/master/ci-4.0)"
after_success:
  - bash <(curl -s https://codecov.io/bash)